#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          4
bspc config ignore_ewmh_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true


bspc rule -a vlc state=floating follow=on
bspc rule -a firefox:Toolkit state=floating follow=on
 


# other stuff...

feh --bg-max ~/.config/backgrounds/background.png --image-bg '#121214' &

wmname LG3D &
sh ~/.config/polybar/hack/launch.sh

startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  touch $startup_lock_file
  echo "bruh moment" > $startup_lock_file
  # stops startup applications getting gunged up with bspc wm -r
  compton &
fi
