background {
  monitor =
  path = /home/ada/.config/backgrounds/cas.jpg  # supports png, jpg, webp (no animations, though)
  color = rgba(25, 20, 20, 1.0)

  # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
  blur_passes = 1 # 0 disables blurring
  blur_size = 3
  noise = 0.0117
  contrast = 0.8916
  brightness = 0.8172
  vibrancy = 0.1696
  vibrancy_darkness = 0.0
}

label {
  text = $TIME
  color = rgba(169, 149, 210, 1.0)
  font_size = 128 
  font_family = Quicksand Bold
  position = 0, 300
  halign = center
  valign = center
}


input-field {
  monitor =
  size = 20%, 5%
  outline_thickness = 2
  inner_color = rgba(0, 0, 0, 0.0) # no fill

  outer_color = rgba(5f457dee) rgba(aa96d5ee) 45deg
  check_color=rgba(595959aa)
  fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg
  font_family = Quicksand Bold
  font_color = rgb(143, 143, 143)
  fade_on_empty = false
  rounding = 5

  capslock_color = rgba(785072ee) rgba(d596a6ee) 60deg
  position = 0, -500
  halign = center
  valign = center
}
