#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a vlc state=floating follow=on
bspc rule -a firefox:Toolkit state=floating follow=on

# Java fixes
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

feh --bg-fill ~/.config/backgrounds/cas.jpg

# Polybar launch
bash ~/.config/polybar/launch.sh --colorblocks

# Framework specific option
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" 332 1 & 
# Start Policy Kit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & 
# Startup applications
lock=/tmp/bspwm-apps.lock
if [ ! -f $lock ]; then
  touch $lock
  echo "# Bspwm Startup Lock" > $lock
  picom & /usr/bin/dunst & systemd-run --user --on-boot=10 --on-unit-active=60 /home/nutmeg/.config/scripts/battery-sadMac.sh & 
fi

